
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox-emptydir
  name: busybox-emptydir
spec:
  containers:
  - image: busybox
    name: busybox-emptydir
    command: ["/bin/sh"]
    args: ["-c","echo 'At Work!' >> /mnt/log.txt; while true; do date >> /mnt/log.txt; sleep 10; done;"]
    volumeMounts:
      - name: my-volume 
        mountPath: "/mnt"
  volumes:
  - name: my-volume
    emptyDir: {}
