apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-gluster-pv
spec:
  capacity:
    storage: 2Gi  # Adjust this based on your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # GlusterFS supports RWX access mode (multiple pods can mount it)
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: glusterfs-cluster
    path: myvolume  # Name of the GlusterFS volume
    readOnly: false
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-gluster-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Same as PV size or less