
apiVersion: v1
kind: Pod
metadata:
  name: glusterfs-hostaliases-pod
spec:
  restartPolicy: Never
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - glusterfs
          topologyKey: "kubernetes.io/hostname"
  hostAliases:
  - ip: "10.244.0.19"
    hostnames:
    - "glusterfs-0.glusterfs-service.default.svc.cluster.local"
    - "glusterfs-0"
  - ip: "10.244.0.20"
    hostnames:
    - "glusterfs-1.glusterfs-service.default.svc.cluster.local"
    - "glusterfs-1"
  - ip: "10.244.0.21"
    hostnames:
    - "glusterfs-2.glusterfs-service.default.svc.cluster.local"
    - "glusterfs-2"
  containers:
  - name: glusterfs
    image: busybox:1.28
    command:
    - cat
    args:
    - "/etc/hosts"
