apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  - addresses:
      - ip: 192.168.49.3  # Replace with the IP of minikube-m02
      - ip: 192.168.49.4  # Replace with the IP of minikube-m03
    ports:
      - port: 24007  # Default GlusterFS port
