apiVersion: v1
kind: Pod
metadata:
  name: my-gluster-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - |
          # Print some initial debugging information
          echo "Starting log generation process..." >> /mnt/gluster/logs/debug.log
          
          # Create the directory for logs if it doesn't exist
          mkdir -p /mnt/gluster/logs
          echo "$(date) - Directory for logs created." >> /mnt/gluster/logs/debug.log
          
          # Start writing logs every minute
          while true; do
            echo "$(date) - Dynamic log entry" >> /mnt/gluster/logs/dynamic_logs.txt
            echo "$(date) - Logged to dynamic_logs.txt" >> /mnt/gluster/logs/debug.log  # Debug log for each entry written
            sleep 60  # Log every 60 seconds (1 minute)
          done
      volumeMounts:
        - name: gluster-volume
          mountPath: /mnt/gluster  # Mount GlusterFS volume here

  volumes:
    - name: gluster-volume
      persistentVolumeClaim:
        claimName: my-gluster-pvc  # The PVC that points to your GlusterFS volume
