apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox-nostorage
  name: busybox-nostorage
spec:
  containers:
  - image: busybox
    name: busybox-nostorage
    command: ["/bin/sh"]
    args: ["-c","echo 'At Work!' >> /var/log.txt; while true;  do date >> /var/log.txt;  sleep 10;  done;"]

