apiVersion: v1
kind: Pod
metadata:
  name: db-app
spec:
  containers:
  - name: db-app-container
    image: nginx
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_HOST
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_NAME
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: db-config
          key: DB_PASSWORD
