apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-html-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    configMap:
      name: nginx-html-config
      items:
        - key: index.html
          path: index.html
