apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-sa-binding
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: ops
roleRef:
  kind: ClusterRole
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io
