apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-provisioner
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pvc
  labels:
    name: busybox-pvc
spec:
  containers:
    - name: busybox-pvc
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo \"Hello, NFS! The time is $(date) for busybox-pvc\" >> /mnt/nfs_share/busybox-pvc.txt; sleep 5; done"]
      volumeMounts:
        - mountPath: /mnt/nfs_share
          name: nfs-volume
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
