apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox-nfs
  name: busybox-nfs
spec:
  containers:
  - image: busybox
    name: busybox-nfs
    command: ["/bin/sh"]
    args: [
      "-c", 
      "echo \"At Work! $(date)\" >> /mnt/busybox-nfs.txt; while true; do date >> /mnt/busybox-nfs.txt; sleep 10; done;"
    ]
    volumeMounts:
      - name: nfs
        mountPath: "/mnt"  # Mount the NFS volume at /mnt
  volumes:
    - name: nfs
      nfs:
        server: 10.100.22.73  # Change this to the IP address of your NFS server
        path: /exports  # Path to export from NFS server
