apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-server-clusterrole
rules:
  # Allow creating and managing events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "get", "list", "update", "delete"]
  # Allow listing and watching resources related to persistent storage
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
