apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-export-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/data 
    server: nfs-server.default.svc.cluster.local 
