
replicaCount: 1

# imagePullSecrets:

image:
  repository: quay.io/kubernetes_incubator/nfs-provisioner
  tag: v2.3.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

  nfsPort: 2049
  nlockmgrPort: 32803
  mountdPort: 20048
  rquotadPort: 875
  rpcbindPort: 111
  statdPort: 662
  # nfsNodePort:
  # nlockmgrNodePort:
  # mountdNodePort:
  # rquotadNodePort:
  # rpcbindNodePort:
  # statdNodePort:

  externalIPs: []

persistence:
  enabled: false

  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  accessMode: ReadWriteOnce
  size: 1Gi

storageClass:
  create: true
  provisionerName: nfs-provisioner
  defaultClass: false
  name: nfs
  allowVolumeExpansion: true
  parameters: {}
  server: "nfs-server.default.svc.cluster.local"
  mountOptions:
    - vers=3
  reclaimPolicy: Delete

rbac:
  create: true
  serviceAccountName: default

resources:
  limits:
    cpu: "3" 
    memory: "5Gi"
  requests:
    cpu: "500m"
    memory: "2Gi" 


nodeSelector: {}

tolerations: []

affinity: {}

