apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: default
type: Opaque
data:
  ssh-private-key: |
    c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDNnVrbSttVS9aWVE1MUNaSGdzVmlScHhUUkE2eTZaZzZ4QjN3cDVoWk5NeC9BQ3RNY3FhK2JnL3NSVEl0U2JBdkJjKzNYMU1XRFlOUml1T3RSNEVGQU9qN2tMd0JveG1ZcjNKL0tZMnpUYUhwVzBIS0w2RWRDMlkrZ2NUVWNkVVlNNmtVWkcwMTZnM0llQ2ppT0ljRWc3TkJBbU1JNXMxVk5tYlJvNitSRHEraFpLTHJnd0gwOEFPbWZsaktsMVVkcHU1SS9wbDAyeitaR0xqRUpNaS9JcTQrTXdSUmsxd0FTMHAxcncyT2ZMR20rYkl3alZsU1JvT1dSWkNwbGVPWTN2dU90OCtJcWlNQ051dFdkZGo5R1BrL2hTNEVZVXNnNjlpTVNHRWRiWmFpQ0txS0tuRks0UlN5bkFDRElhaGlxeDRoKzVZOEl5bWdBRTJicld6UXggZWx2aXNuZ3dlc3NlQE1hY0Jvb2tQcm8udWx0cmFodWIK


