apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-ssh-pod
  namespace: default
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:20.04
      ports:
        - containerPort: 22
      command:
        - "/bin/bash"
        - "-c"
        - |
          apt update && \
          apt install -y openssh-server && \
          mkdir /var/run/sshd && \
          mkdir -p /root/.ssh && \
          echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
          echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config && \
          echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && \
          # Assuming the SSH public key is in the Secret (authorized_keys)
          mkdir -p /root/.ssh && \
          cp /root/.ssh/id_rsa /root/.ssh/authorized_keys && \
          chmod 600 /root/.ssh/authorized_keys && \
          chmod 700 /root/.ssh && \
          /usr/sbin/sshd -D
      volumeMounts:
        - name: ssh-key-volume
          mountPath: /root/.ssh/id_rsa
          subPath: id_rsa
          readOnly: true
  volumes:
    - name: ssh-key-volume
      secret:
        secretName: ssh-key-secret
        items:
          - key: ssh-private-key
            path: id_rsa
